name: 'nutritrack'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nutritrack:
    bronze:
      +database: "NUTRITRACK_{{ env_var('DBT_ENVIRONMENTS') }}_BRONZE_DB"
      +schema: bronze
      +materialized: view
    silver:
      +database: "NUTRITRACK_{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
      +schema: silver
      +materialized: view
    gold:
      +database: "NUTRITRACK_{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
      +schema: gold
      +materialized: table

snapshots:
  nutritrack:
    +target_schema: snapshots
    +target_database: "NUTRITRACK_{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"